version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
    volumes:
     - localstack_data:/var/lib/localstack
     - /var/run/docker.sock:/var/run/docker.sock

  videomanager.api:
    image: ${DOCKER_REGISTRY-}videomanagerapi
    container_name: videomanager.api
    build:
      context: .
      dockerfile: VideoManager.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      -  videomanager.postgres
      - localstack
    command: >
      sh -c "until pg_isready -h postgres -p 5432 -U postgres; do echo 'Aguardando PostgreSQL...'; sleep 2; done &&
      dotnet VideoManager.API.dll"

  videomanager.postgres:
    image: postgres:latest
    container_name: videomanager.postgres
    ports:
      - "5432:5432"   
    environment:
      - POSTGRES_DB=VideoManager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  localstack_data:
  postgres_data:
